# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



################################################################################
#  xio library                                                                 #
################################################################################




pkgdatadir = $(datadir)/xio
pkgincludedir = $(includedir)/xio
pkglibdir = $(libdir)/xio
pkglibexecdir = $(libexecdir)/xio
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure $(xinclude_HEADERS) AUTHORS COPYING \
	ChangeLog INSTALL NEWS config.guess config.sub depcomp \
	install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)" \
	"$(DESTDIR)$(xincludedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libxio_la_LIBADD =
am__objects_1 = transport.lo ipc_getopt.lo ipc_setopt.lo ipc.lo \
	timer.lo condition.lo taskpool.lo mutex.lo eventloop.lo \
	filepath.lo krb.lo alloc.lo spinlock.lo krb_augmented.lo \
	efd.lo waitgroup.lo thread.lo atomic.lo module.lo tcp.lo \
	tcp_getopt.lo tcp_setopt.lo bufio.lo modstat.lo slab.lo \
	crc16.lo sockaddr.lo
am__objects_2 = xsetsockopt.lo xlisten.lo xmul_listener.lo xsend.lo \
	xrecv.lo xeventnotify.lo xcpu.lo xbind.lo xgb.lo xclose.lo \
	xconnect.lo xtcpipc_listener.lo xtcpipc.lo xsock.lo \
	xgetsockopt.lo xmsg.lo xinproc.lo xinproc_listener.lo
am__objects_3 = xpoll_struct.lo xselect.lo xeventpoll.lo
am__objects_4 = sp_module.lo sp_getopt.lo sp_close.lo sp_add.lo \
	sp_endpoint.lo sp_send.lo pipeline.lo rep_ep.lo req_ep.lo \
	sp_rm.lo sp_hdr.lo sp_recv.lo sp_setopt.lo
am_libxio_la_OBJECTS = $(am__objects_1) $(am__objects_2) \
	$(am__objects_3) $(am__objects_4)
libxio_la_OBJECTS = $(am_libxio_la_OBJECTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libxio_la_SOURCES)
DIST_SOURCES = $(libxio_la_SOURCES)
DATA = $(pkgconfig_DATA)
HEADERS = $(xinclude_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/fangdong/work/xio/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/fangdong/work/xio/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/fangdong/work/xio/missing --run autoconf
AUTOHEADER = ${SHELL} /home/fangdong/work/xio/missing --run autoheader
AUTOMAKE = ${SHELL} /home/fangdong/work/xio/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/fangdong/work/xio/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = xio
PACKAGE_BUGREPORT = yp.fangdong@gmail.com
PACKAGE_NAME = xio
PACKAGE_STRING = xio 0.9
PACKAGE_TARNAME = xio
PACKAGE_VERSION = 0.9
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.9
abs_builddir = /home/fangdong/work/xio
abs_srcdir = /home/fangdong/work/xio
abs_top_builddir = /home/fangdong/work/xio
abs_top_srcdir = /home/fangdong/work/xio
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/fangdong/work/xio/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
EXTRA_DIST = 
INCLUDES = -I$(top_srcdir)/include -I$(top_srcdir)/src/
xincludedir = $(includedir)/xio
xinclude_HEADERS = \
	include/xio/poll.h \
	include/xio/cplusplus_endif.h \
	include/xio/sp_reqrep.h \
	include/xio/cmsghdr.h \
	include/xio/cplusplus_define.h \
	include/xio/sp.h \
	include/xio/socket.h

lib_LTLIBRARIES = libxio.la
XIO_SOCKET = \
	src/socket/xsetsockopt.c \
	src/socket/xgb.h \
	src/socket/xlisten.c \
	src/socket/mul/xmul_listener.c \
	src/socket/xsend.c \
	src/socket/xsock.h \
	src/socket/xrecv.c \
	src/socket/xeventnotify.c \
	src/socket/xcpu.c \
	src/socket/xbind.c \
	src/socket/xgb.c \
	src/socket/xclose.c \
	src/socket/xconnect.c \
	src/socket/tcp/xtcpipc_listener.c \
	src/socket/tcp/xtcpipc.c \
	src/socket/xsock.c \
	src/socket/xmsg.h \
	src/socket/xgetsockopt.c \
	src/socket/xinproc.h \
	src/socket/xmsg.c \
	src/socket/xtcpipc.h \
	src/socket/inproc/xinproc.c \
	src/socket/inproc/xinproc_listener.c \
	src/socket/xcpu.h

XIO_POLL = \
	src/poll/xeventpoll.h \
	src/poll/xpoll_struct.c \
	src/poll/xselect.c \
	src/poll/xeventpoll.c

XIO_SP = \
	src/sp/sp_module.c \
	src/sp/sp_getopt.c \
	src/sp/sp_close.c \
	src/sp/sp_add.c \
	src/sp/sp_endpoint.c \
	src/sp/bus/bus.h \
	src/sp/sp_send.c \
	src/sp/reqrep/req_ep.h \
	src/sp/reqrep/pipeline.c \
	src/sp/reqrep/rep_ep.c \
	src/sp/reqrep/rep_ep.h \
	src/sp/reqrep/req_ep.c \
	src/sp/sp_rm.c \
	src/sp/sp_hdr.c \
	src/sp/pubsub/sub.h \
	src/sp/pubsub/pub.h \
	src/sp/sp_recv.c \
	src/sp/sp_hdr.h \
	src/sp/sp_setopt.c \
	src/sp/sp_module.h

XIO_UTILS = \
	src/utils/spinlock.h \
	src/utils/transport.c \
	src/utils/ipc/ipc_getopt.c \
	src/utils/ipc/ipc_setopt.c \
	src/utils/ipc/ipc.c \
	src/utils/ipc/ipc.h \
	src/utils/bufio.h \
	src/utils/timer.c \
	src/utils/condition.c \
	src/utils/filepath.h \
	src/utils/skrb_sync.h \
	src/utils/taskpool.c \
	src/utils/mutex.c \
	src/utils/alloc.h \
	src/utils/timer.h \
	src/utils/eventloop.c \
	src/utils/filepath.c \
	src/utils/base.h \
	src/utils/atomic.h \
	src/utils/krb.c \
	src/utils/skrb.h \
	src/utils/map.h \
	src/utils/list.h \
	src/utils/efd.h \
	src/utils/alloc.c \
	src/utils/thread.h \
	src/utils/crc.h \
	src/utils/krb.h \
	src/utils/krb_augmented.h \
	src/utils/condition.h \
	src/utils/spinlock.c \
	src/utils/krb_augmented.c \
	src/utils/efd.c \
	src/utils/modstat.h \
	src/utils/waitgroup.c \
	src/utils/taskpool.h \
	src/utils/thread.c \
	src/utils/atomic.c \
	src/utils/module.c \
	src/utils/tcp/tcp.c \
	src/utils/tcp/tcp.h \
	src/utils/tcp/tcp_getopt.c \
	src/utils/tcp/tcp_setopt.c \
	src/utils/bufio.c \
	src/utils/modstat.c \
	src/utils/slab.h \
	src/utils/slab.c \
	src/utils/crc16.c \
	src/utils/sockaddr.c \
	src/utils/sockaddr.h \
	src/utils/waitgroup.h \
	src/utils/eventloop.h \
	src/utils/transport.h \
	src/utils/mutex.h

libxio_la_SOURCES = \
	$(XIO_UTILS) \
	$(XIO_SOCKET) \
	$(XIO_POLL) \
	$(XIO_SP)

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = libxio.pc
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libxio.la: $(libxio_la_OBJECTS) $(libxio_la_DEPENDENCIES) 
	$(LINK) -rpath $(libdir) $(libxio_la_OBJECTS) $(libxio_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/alloc.Plo
include ./$(DEPDIR)/atomic.Plo
include ./$(DEPDIR)/bufio.Plo
include ./$(DEPDIR)/condition.Plo
include ./$(DEPDIR)/crc16.Plo
include ./$(DEPDIR)/efd.Plo
include ./$(DEPDIR)/eventloop.Plo
include ./$(DEPDIR)/filepath.Plo
include ./$(DEPDIR)/ipc.Plo
include ./$(DEPDIR)/ipc_getopt.Plo
include ./$(DEPDIR)/ipc_setopt.Plo
include ./$(DEPDIR)/krb.Plo
include ./$(DEPDIR)/krb_augmented.Plo
include ./$(DEPDIR)/modstat.Plo
include ./$(DEPDIR)/module.Plo
include ./$(DEPDIR)/mutex.Plo
include ./$(DEPDIR)/pipeline.Plo
include ./$(DEPDIR)/rep_ep.Plo
include ./$(DEPDIR)/req_ep.Plo
include ./$(DEPDIR)/slab.Plo
include ./$(DEPDIR)/sockaddr.Plo
include ./$(DEPDIR)/sp_add.Plo
include ./$(DEPDIR)/sp_close.Plo
include ./$(DEPDIR)/sp_endpoint.Plo
include ./$(DEPDIR)/sp_getopt.Plo
include ./$(DEPDIR)/sp_hdr.Plo
include ./$(DEPDIR)/sp_module.Plo
include ./$(DEPDIR)/sp_recv.Plo
include ./$(DEPDIR)/sp_rm.Plo
include ./$(DEPDIR)/sp_send.Plo
include ./$(DEPDIR)/sp_setopt.Plo
include ./$(DEPDIR)/spinlock.Plo
include ./$(DEPDIR)/taskpool.Plo
include ./$(DEPDIR)/tcp.Plo
include ./$(DEPDIR)/tcp_getopt.Plo
include ./$(DEPDIR)/tcp_setopt.Plo
include ./$(DEPDIR)/thread.Plo
include ./$(DEPDIR)/timer.Plo
include ./$(DEPDIR)/transport.Plo
include ./$(DEPDIR)/waitgroup.Plo
include ./$(DEPDIR)/xbind.Plo
include ./$(DEPDIR)/xclose.Plo
include ./$(DEPDIR)/xconnect.Plo
include ./$(DEPDIR)/xcpu.Plo
include ./$(DEPDIR)/xeventnotify.Plo
include ./$(DEPDIR)/xeventpoll.Plo
include ./$(DEPDIR)/xgb.Plo
include ./$(DEPDIR)/xgetsockopt.Plo
include ./$(DEPDIR)/xinproc.Plo
include ./$(DEPDIR)/xinproc_listener.Plo
include ./$(DEPDIR)/xlisten.Plo
include ./$(DEPDIR)/xmsg.Plo
include ./$(DEPDIR)/xmul_listener.Plo
include ./$(DEPDIR)/xpoll_struct.Plo
include ./$(DEPDIR)/xrecv.Plo
include ./$(DEPDIR)/xselect.Plo
include ./$(DEPDIR)/xsend.Plo
include ./$(DEPDIR)/xsetsockopt.Plo
include ./$(DEPDIR)/xsock.Plo
include ./$(DEPDIR)/xtcpipc.Plo
include ./$(DEPDIR)/xtcpipc_listener.Plo

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

transport.lo: src/utils/transport.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT transport.lo -MD -MP -MF $(DEPDIR)/transport.Tpo -c -o transport.lo `test -f 'src/utils/transport.c' || echo '$(srcdir)/'`src/utils/transport.c
	$(am__mv) $(DEPDIR)/transport.Tpo $(DEPDIR)/transport.Plo
#	source='src/utils/transport.c' object='transport.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o transport.lo `test -f 'src/utils/transport.c' || echo '$(srcdir)/'`src/utils/transport.c

ipc_getopt.lo: src/utils/ipc/ipc_getopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ipc_getopt.lo -MD -MP -MF $(DEPDIR)/ipc_getopt.Tpo -c -o ipc_getopt.lo `test -f 'src/utils/ipc/ipc_getopt.c' || echo '$(srcdir)/'`src/utils/ipc/ipc_getopt.c
	$(am__mv) $(DEPDIR)/ipc_getopt.Tpo $(DEPDIR)/ipc_getopt.Plo
#	source='src/utils/ipc/ipc_getopt.c' object='ipc_getopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ipc_getopt.lo `test -f 'src/utils/ipc/ipc_getopt.c' || echo '$(srcdir)/'`src/utils/ipc/ipc_getopt.c

ipc_setopt.lo: src/utils/ipc/ipc_setopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ipc_setopt.lo -MD -MP -MF $(DEPDIR)/ipc_setopt.Tpo -c -o ipc_setopt.lo `test -f 'src/utils/ipc/ipc_setopt.c' || echo '$(srcdir)/'`src/utils/ipc/ipc_setopt.c
	$(am__mv) $(DEPDIR)/ipc_setopt.Tpo $(DEPDIR)/ipc_setopt.Plo
#	source='src/utils/ipc/ipc_setopt.c' object='ipc_setopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ipc_setopt.lo `test -f 'src/utils/ipc/ipc_setopt.c' || echo '$(srcdir)/'`src/utils/ipc/ipc_setopt.c

ipc.lo: src/utils/ipc/ipc.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ipc.lo -MD -MP -MF $(DEPDIR)/ipc.Tpo -c -o ipc.lo `test -f 'src/utils/ipc/ipc.c' || echo '$(srcdir)/'`src/utils/ipc/ipc.c
	$(am__mv) $(DEPDIR)/ipc.Tpo $(DEPDIR)/ipc.Plo
#	source='src/utils/ipc/ipc.c' object='ipc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ipc.lo `test -f 'src/utils/ipc/ipc.c' || echo '$(srcdir)/'`src/utils/ipc/ipc.c

timer.lo: src/utils/timer.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT timer.lo -MD -MP -MF $(DEPDIR)/timer.Tpo -c -o timer.lo `test -f 'src/utils/timer.c' || echo '$(srcdir)/'`src/utils/timer.c
	$(am__mv) $(DEPDIR)/timer.Tpo $(DEPDIR)/timer.Plo
#	source='src/utils/timer.c' object='timer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o timer.lo `test -f 'src/utils/timer.c' || echo '$(srcdir)/'`src/utils/timer.c

condition.lo: src/utils/condition.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT condition.lo -MD -MP -MF $(DEPDIR)/condition.Tpo -c -o condition.lo `test -f 'src/utils/condition.c' || echo '$(srcdir)/'`src/utils/condition.c
	$(am__mv) $(DEPDIR)/condition.Tpo $(DEPDIR)/condition.Plo
#	source='src/utils/condition.c' object='condition.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o condition.lo `test -f 'src/utils/condition.c' || echo '$(srcdir)/'`src/utils/condition.c

taskpool.lo: src/utils/taskpool.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT taskpool.lo -MD -MP -MF $(DEPDIR)/taskpool.Tpo -c -o taskpool.lo `test -f 'src/utils/taskpool.c' || echo '$(srcdir)/'`src/utils/taskpool.c
	$(am__mv) $(DEPDIR)/taskpool.Tpo $(DEPDIR)/taskpool.Plo
#	source='src/utils/taskpool.c' object='taskpool.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o taskpool.lo `test -f 'src/utils/taskpool.c' || echo '$(srcdir)/'`src/utils/taskpool.c

mutex.lo: src/utils/mutex.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT mutex.lo -MD -MP -MF $(DEPDIR)/mutex.Tpo -c -o mutex.lo `test -f 'src/utils/mutex.c' || echo '$(srcdir)/'`src/utils/mutex.c
	$(am__mv) $(DEPDIR)/mutex.Tpo $(DEPDIR)/mutex.Plo
#	source='src/utils/mutex.c' object='mutex.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o mutex.lo `test -f 'src/utils/mutex.c' || echo '$(srcdir)/'`src/utils/mutex.c

eventloop.lo: src/utils/eventloop.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT eventloop.lo -MD -MP -MF $(DEPDIR)/eventloop.Tpo -c -o eventloop.lo `test -f 'src/utils/eventloop.c' || echo '$(srcdir)/'`src/utils/eventloop.c
	$(am__mv) $(DEPDIR)/eventloop.Tpo $(DEPDIR)/eventloop.Plo
#	source='src/utils/eventloop.c' object='eventloop.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o eventloop.lo `test -f 'src/utils/eventloop.c' || echo '$(srcdir)/'`src/utils/eventloop.c

filepath.lo: src/utils/filepath.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT filepath.lo -MD -MP -MF $(DEPDIR)/filepath.Tpo -c -o filepath.lo `test -f 'src/utils/filepath.c' || echo '$(srcdir)/'`src/utils/filepath.c
	$(am__mv) $(DEPDIR)/filepath.Tpo $(DEPDIR)/filepath.Plo
#	source='src/utils/filepath.c' object='filepath.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o filepath.lo `test -f 'src/utils/filepath.c' || echo '$(srcdir)/'`src/utils/filepath.c

krb.lo: src/utils/krb.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT krb.lo -MD -MP -MF $(DEPDIR)/krb.Tpo -c -o krb.lo `test -f 'src/utils/krb.c' || echo '$(srcdir)/'`src/utils/krb.c
	$(am__mv) $(DEPDIR)/krb.Tpo $(DEPDIR)/krb.Plo
#	source='src/utils/krb.c' object='krb.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o krb.lo `test -f 'src/utils/krb.c' || echo '$(srcdir)/'`src/utils/krb.c

alloc.lo: src/utils/alloc.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT alloc.lo -MD -MP -MF $(DEPDIR)/alloc.Tpo -c -o alloc.lo `test -f 'src/utils/alloc.c' || echo '$(srcdir)/'`src/utils/alloc.c
	$(am__mv) $(DEPDIR)/alloc.Tpo $(DEPDIR)/alloc.Plo
#	source='src/utils/alloc.c' object='alloc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o alloc.lo `test -f 'src/utils/alloc.c' || echo '$(srcdir)/'`src/utils/alloc.c

spinlock.lo: src/utils/spinlock.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT spinlock.lo -MD -MP -MF $(DEPDIR)/spinlock.Tpo -c -o spinlock.lo `test -f 'src/utils/spinlock.c' || echo '$(srcdir)/'`src/utils/spinlock.c
	$(am__mv) $(DEPDIR)/spinlock.Tpo $(DEPDIR)/spinlock.Plo
#	source='src/utils/spinlock.c' object='spinlock.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o spinlock.lo `test -f 'src/utils/spinlock.c' || echo '$(srcdir)/'`src/utils/spinlock.c

krb_augmented.lo: src/utils/krb_augmented.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT krb_augmented.lo -MD -MP -MF $(DEPDIR)/krb_augmented.Tpo -c -o krb_augmented.lo `test -f 'src/utils/krb_augmented.c' || echo '$(srcdir)/'`src/utils/krb_augmented.c
	$(am__mv) $(DEPDIR)/krb_augmented.Tpo $(DEPDIR)/krb_augmented.Plo
#	source='src/utils/krb_augmented.c' object='krb_augmented.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o krb_augmented.lo `test -f 'src/utils/krb_augmented.c' || echo '$(srcdir)/'`src/utils/krb_augmented.c

efd.lo: src/utils/efd.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT efd.lo -MD -MP -MF $(DEPDIR)/efd.Tpo -c -o efd.lo `test -f 'src/utils/efd.c' || echo '$(srcdir)/'`src/utils/efd.c
	$(am__mv) $(DEPDIR)/efd.Tpo $(DEPDIR)/efd.Plo
#	source='src/utils/efd.c' object='efd.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o efd.lo `test -f 'src/utils/efd.c' || echo '$(srcdir)/'`src/utils/efd.c

waitgroup.lo: src/utils/waitgroup.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT waitgroup.lo -MD -MP -MF $(DEPDIR)/waitgroup.Tpo -c -o waitgroup.lo `test -f 'src/utils/waitgroup.c' || echo '$(srcdir)/'`src/utils/waitgroup.c
	$(am__mv) $(DEPDIR)/waitgroup.Tpo $(DEPDIR)/waitgroup.Plo
#	source='src/utils/waitgroup.c' object='waitgroup.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o waitgroup.lo `test -f 'src/utils/waitgroup.c' || echo '$(srcdir)/'`src/utils/waitgroup.c

thread.lo: src/utils/thread.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT thread.lo -MD -MP -MF $(DEPDIR)/thread.Tpo -c -o thread.lo `test -f 'src/utils/thread.c' || echo '$(srcdir)/'`src/utils/thread.c
	$(am__mv) $(DEPDIR)/thread.Tpo $(DEPDIR)/thread.Plo
#	source='src/utils/thread.c' object='thread.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o thread.lo `test -f 'src/utils/thread.c' || echo '$(srcdir)/'`src/utils/thread.c

atomic.lo: src/utils/atomic.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT atomic.lo -MD -MP -MF $(DEPDIR)/atomic.Tpo -c -o atomic.lo `test -f 'src/utils/atomic.c' || echo '$(srcdir)/'`src/utils/atomic.c
	$(am__mv) $(DEPDIR)/atomic.Tpo $(DEPDIR)/atomic.Plo
#	source='src/utils/atomic.c' object='atomic.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o atomic.lo `test -f 'src/utils/atomic.c' || echo '$(srcdir)/'`src/utils/atomic.c

module.lo: src/utils/module.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT module.lo -MD -MP -MF $(DEPDIR)/module.Tpo -c -o module.lo `test -f 'src/utils/module.c' || echo '$(srcdir)/'`src/utils/module.c
	$(am__mv) $(DEPDIR)/module.Tpo $(DEPDIR)/module.Plo
#	source='src/utils/module.c' object='module.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o module.lo `test -f 'src/utils/module.c' || echo '$(srcdir)/'`src/utils/module.c

tcp.lo: src/utils/tcp/tcp.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tcp.lo -MD -MP -MF $(DEPDIR)/tcp.Tpo -c -o tcp.lo `test -f 'src/utils/tcp/tcp.c' || echo '$(srcdir)/'`src/utils/tcp/tcp.c
	$(am__mv) $(DEPDIR)/tcp.Tpo $(DEPDIR)/tcp.Plo
#	source='src/utils/tcp/tcp.c' object='tcp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tcp.lo `test -f 'src/utils/tcp/tcp.c' || echo '$(srcdir)/'`src/utils/tcp/tcp.c

tcp_getopt.lo: src/utils/tcp/tcp_getopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tcp_getopt.lo -MD -MP -MF $(DEPDIR)/tcp_getopt.Tpo -c -o tcp_getopt.lo `test -f 'src/utils/tcp/tcp_getopt.c' || echo '$(srcdir)/'`src/utils/tcp/tcp_getopt.c
	$(am__mv) $(DEPDIR)/tcp_getopt.Tpo $(DEPDIR)/tcp_getopt.Plo
#	source='src/utils/tcp/tcp_getopt.c' object='tcp_getopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tcp_getopt.lo `test -f 'src/utils/tcp/tcp_getopt.c' || echo '$(srcdir)/'`src/utils/tcp/tcp_getopt.c

tcp_setopt.lo: src/utils/tcp/tcp_setopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tcp_setopt.lo -MD -MP -MF $(DEPDIR)/tcp_setopt.Tpo -c -o tcp_setopt.lo `test -f 'src/utils/tcp/tcp_setopt.c' || echo '$(srcdir)/'`src/utils/tcp/tcp_setopt.c
	$(am__mv) $(DEPDIR)/tcp_setopt.Tpo $(DEPDIR)/tcp_setopt.Plo
#	source='src/utils/tcp/tcp_setopt.c' object='tcp_setopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tcp_setopt.lo `test -f 'src/utils/tcp/tcp_setopt.c' || echo '$(srcdir)/'`src/utils/tcp/tcp_setopt.c

bufio.lo: src/utils/bufio.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT bufio.lo -MD -MP -MF $(DEPDIR)/bufio.Tpo -c -o bufio.lo `test -f 'src/utils/bufio.c' || echo '$(srcdir)/'`src/utils/bufio.c
	$(am__mv) $(DEPDIR)/bufio.Tpo $(DEPDIR)/bufio.Plo
#	source='src/utils/bufio.c' object='bufio.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o bufio.lo `test -f 'src/utils/bufio.c' || echo '$(srcdir)/'`src/utils/bufio.c

modstat.lo: src/utils/modstat.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT modstat.lo -MD -MP -MF $(DEPDIR)/modstat.Tpo -c -o modstat.lo `test -f 'src/utils/modstat.c' || echo '$(srcdir)/'`src/utils/modstat.c
	$(am__mv) $(DEPDIR)/modstat.Tpo $(DEPDIR)/modstat.Plo
#	source='src/utils/modstat.c' object='modstat.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o modstat.lo `test -f 'src/utils/modstat.c' || echo '$(srcdir)/'`src/utils/modstat.c

slab.lo: src/utils/slab.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT slab.lo -MD -MP -MF $(DEPDIR)/slab.Tpo -c -o slab.lo `test -f 'src/utils/slab.c' || echo '$(srcdir)/'`src/utils/slab.c
	$(am__mv) $(DEPDIR)/slab.Tpo $(DEPDIR)/slab.Plo
#	source='src/utils/slab.c' object='slab.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o slab.lo `test -f 'src/utils/slab.c' || echo '$(srcdir)/'`src/utils/slab.c

crc16.lo: src/utils/crc16.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT crc16.lo -MD -MP -MF $(DEPDIR)/crc16.Tpo -c -o crc16.lo `test -f 'src/utils/crc16.c' || echo '$(srcdir)/'`src/utils/crc16.c
	$(am__mv) $(DEPDIR)/crc16.Tpo $(DEPDIR)/crc16.Plo
#	source='src/utils/crc16.c' object='crc16.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o crc16.lo `test -f 'src/utils/crc16.c' || echo '$(srcdir)/'`src/utils/crc16.c

sockaddr.lo: src/utils/sockaddr.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sockaddr.lo -MD -MP -MF $(DEPDIR)/sockaddr.Tpo -c -o sockaddr.lo `test -f 'src/utils/sockaddr.c' || echo '$(srcdir)/'`src/utils/sockaddr.c
	$(am__mv) $(DEPDIR)/sockaddr.Tpo $(DEPDIR)/sockaddr.Plo
#	source='src/utils/sockaddr.c' object='sockaddr.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sockaddr.lo `test -f 'src/utils/sockaddr.c' || echo '$(srcdir)/'`src/utils/sockaddr.c

xsetsockopt.lo: src/socket/xsetsockopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xsetsockopt.lo -MD -MP -MF $(DEPDIR)/xsetsockopt.Tpo -c -o xsetsockopt.lo `test -f 'src/socket/xsetsockopt.c' || echo '$(srcdir)/'`src/socket/xsetsockopt.c
	$(am__mv) $(DEPDIR)/xsetsockopt.Tpo $(DEPDIR)/xsetsockopt.Plo
#	source='src/socket/xsetsockopt.c' object='xsetsockopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xsetsockopt.lo `test -f 'src/socket/xsetsockopt.c' || echo '$(srcdir)/'`src/socket/xsetsockopt.c

xlisten.lo: src/socket/xlisten.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xlisten.lo -MD -MP -MF $(DEPDIR)/xlisten.Tpo -c -o xlisten.lo `test -f 'src/socket/xlisten.c' || echo '$(srcdir)/'`src/socket/xlisten.c
	$(am__mv) $(DEPDIR)/xlisten.Tpo $(DEPDIR)/xlisten.Plo
#	source='src/socket/xlisten.c' object='xlisten.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xlisten.lo `test -f 'src/socket/xlisten.c' || echo '$(srcdir)/'`src/socket/xlisten.c

xmul_listener.lo: src/socket/mul/xmul_listener.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xmul_listener.lo -MD -MP -MF $(DEPDIR)/xmul_listener.Tpo -c -o xmul_listener.lo `test -f 'src/socket/mul/xmul_listener.c' || echo '$(srcdir)/'`src/socket/mul/xmul_listener.c
	$(am__mv) $(DEPDIR)/xmul_listener.Tpo $(DEPDIR)/xmul_listener.Plo
#	source='src/socket/mul/xmul_listener.c' object='xmul_listener.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xmul_listener.lo `test -f 'src/socket/mul/xmul_listener.c' || echo '$(srcdir)/'`src/socket/mul/xmul_listener.c

xsend.lo: src/socket/xsend.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xsend.lo -MD -MP -MF $(DEPDIR)/xsend.Tpo -c -o xsend.lo `test -f 'src/socket/xsend.c' || echo '$(srcdir)/'`src/socket/xsend.c
	$(am__mv) $(DEPDIR)/xsend.Tpo $(DEPDIR)/xsend.Plo
#	source='src/socket/xsend.c' object='xsend.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xsend.lo `test -f 'src/socket/xsend.c' || echo '$(srcdir)/'`src/socket/xsend.c

xrecv.lo: src/socket/xrecv.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xrecv.lo -MD -MP -MF $(DEPDIR)/xrecv.Tpo -c -o xrecv.lo `test -f 'src/socket/xrecv.c' || echo '$(srcdir)/'`src/socket/xrecv.c
	$(am__mv) $(DEPDIR)/xrecv.Tpo $(DEPDIR)/xrecv.Plo
#	source='src/socket/xrecv.c' object='xrecv.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xrecv.lo `test -f 'src/socket/xrecv.c' || echo '$(srcdir)/'`src/socket/xrecv.c

xeventnotify.lo: src/socket/xeventnotify.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xeventnotify.lo -MD -MP -MF $(DEPDIR)/xeventnotify.Tpo -c -o xeventnotify.lo `test -f 'src/socket/xeventnotify.c' || echo '$(srcdir)/'`src/socket/xeventnotify.c
	$(am__mv) $(DEPDIR)/xeventnotify.Tpo $(DEPDIR)/xeventnotify.Plo
#	source='src/socket/xeventnotify.c' object='xeventnotify.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xeventnotify.lo `test -f 'src/socket/xeventnotify.c' || echo '$(srcdir)/'`src/socket/xeventnotify.c

xcpu.lo: src/socket/xcpu.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xcpu.lo -MD -MP -MF $(DEPDIR)/xcpu.Tpo -c -o xcpu.lo `test -f 'src/socket/xcpu.c' || echo '$(srcdir)/'`src/socket/xcpu.c
	$(am__mv) $(DEPDIR)/xcpu.Tpo $(DEPDIR)/xcpu.Plo
#	source='src/socket/xcpu.c' object='xcpu.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xcpu.lo `test -f 'src/socket/xcpu.c' || echo '$(srcdir)/'`src/socket/xcpu.c

xbind.lo: src/socket/xbind.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xbind.lo -MD -MP -MF $(DEPDIR)/xbind.Tpo -c -o xbind.lo `test -f 'src/socket/xbind.c' || echo '$(srcdir)/'`src/socket/xbind.c
	$(am__mv) $(DEPDIR)/xbind.Tpo $(DEPDIR)/xbind.Plo
#	source='src/socket/xbind.c' object='xbind.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xbind.lo `test -f 'src/socket/xbind.c' || echo '$(srcdir)/'`src/socket/xbind.c

xgb.lo: src/socket/xgb.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xgb.lo -MD -MP -MF $(DEPDIR)/xgb.Tpo -c -o xgb.lo `test -f 'src/socket/xgb.c' || echo '$(srcdir)/'`src/socket/xgb.c
	$(am__mv) $(DEPDIR)/xgb.Tpo $(DEPDIR)/xgb.Plo
#	source='src/socket/xgb.c' object='xgb.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xgb.lo `test -f 'src/socket/xgb.c' || echo '$(srcdir)/'`src/socket/xgb.c

xclose.lo: src/socket/xclose.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xclose.lo -MD -MP -MF $(DEPDIR)/xclose.Tpo -c -o xclose.lo `test -f 'src/socket/xclose.c' || echo '$(srcdir)/'`src/socket/xclose.c
	$(am__mv) $(DEPDIR)/xclose.Tpo $(DEPDIR)/xclose.Plo
#	source='src/socket/xclose.c' object='xclose.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xclose.lo `test -f 'src/socket/xclose.c' || echo '$(srcdir)/'`src/socket/xclose.c

xconnect.lo: src/socket/xconnect.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xconnect.lo -MD -MP -MF $(DEPDIR)/xconnect.Tpo -c -o xconnect.lo `test -f 'src/socket/xconnect.c' || echo '$(srcdir)/'`src/socket/xconnect.c
	$(am__mv) $(DEPDIR)/xconnect.Tpo $(DEPDIR)/xconnect.Plo
#	source='src/socket/xconnect.c' object='xconnect.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xconnect.lo `test -f 'src/socket/xconnect.c' || echo '$(srcdir)/'`src/socket/xconnect.c

xtcpipc_listener.lo: src/socket/tcp/xtcpipc_listener.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xtcpipc_listener.lo -MD -MP -MF $(DEPDIR)/xtcpipc_listener.Tpo -c -o xtcpipc_listener.lo `test -f 'src/socket/tcp/xtcpipc_listener.c' || echo '$(srcdir)/'`src/socket/tcp/xtcpipc_listener.c
	$(am__mv) $(DEPDIR)/xtcpipc_listener.Tpo $(DEPDIR)/xtcpipc_listener.Plo
#	source='src/socket/tcp/xtcpipc_listener.c' object='xtcpipc_listener.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xtcpipc_listener.lo `test -f 'src/socket/tcp/xtcpipc_listener.c' || echo '$(srcdir)/'`src/socket/tcp/xtcpipc_listener.c

xtcpipc.lo: src/socket/tcp/xtcpipc.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xtcpipc.lo -MD -MP -MF $(DEPDIR)/xtcpipc.Tpo -c -o xtcpipc.lo `test -f 'src/socket/tcp/xtcpipc.c' || echo '$(srcdir)/'`src/socket/tcp/xtcpipc.c
	$(am__mv) $(DEPDIR)/xtcpipc.Tpo $(DEPDIR)/xtcpipc.Plo
#	source='src/socket/tcp/xtcpipc.c' object='xtcpipc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xtcpipc.lo `test -f 'src/socket/tcp/xtcpipc.c' || echo '$(srcdir)/'`src/socket/tcp/xtcpipc.c

xsock.lo: src/socket/xsock.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xsock.lo -MD -MP -MF $(DEPDIR)/xsock.Tpo -c -o xsock.lo `test -f 'src/socket/xsock.c' || echo '$(srcdir)/'`src/socket/xsock.c
	$(am__mv) $(DEPDIR)/xsock.Tpo $(DEPDIR)/xsock.Plo
#	source='src/socket/xsock.c' object='xsock.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xsock.lo `test -f 'src/socket/xsock.c' || echo '$(srcdir)/'`src/socket/xsock.c

xgetsockopt.lo: src/socket/xgetsockopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xgetsockopt.lo -MD -MP -MF $(DEPDIR)/xgetsockopt.Tpo -c -o xgetsockopt.lo `test -f 'src/socket/xgetsockopt.c' || echo '$(srcdir)/'`src/socket/xgetsockopt.c
	$(am__mv) $(DEPDIR)/xgetsockopt.Tpo $(DEPDIR)/xgetsockopt.Plo
#	source='src/socket/xgetsockopt.c' object='xgetsockopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xgetsockopt.lo `test -f 'src/socket/xgetsockopt.c' || echo '$(srcdir)/'`src/socket/xgetsockopt.c

xmsg.lo: src/socket/xmsg.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xmsg.lo -MD -MP -MF $(DEPDIR)/xmsg.Tpo -c -o xmsg.lo `test -f 'src/socket/xmsg.c' || echo '$(srcdir)/'`src/socket/xmsg.c
	$(am__mv) $(DEPDIR)/xmsg.Tpo $(DEPDIR)/xmsg.Plo
#	source='src/socket/xmsg.c' object='xmsg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xmsg.lo `test -f 'src/socket/xmsg.c' || echo '$(srcdir)/'`src/socket/xmsg.c

xinproc.lo: src/socket/inproc/xinproc.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xinproc.lo -MD -MP -MF $(DEPDIR)/xinproc.Tpo -c -o xinproc.lo `test -f 'src/socket/inproc/xinproc.c' || echo '$(srcdir)/'`src/socket/inproc/xinproc.c
	$(am__mv) $(DEPDIR)/xinproc.Tpo $(DEPDIR)/xinproc.Plo
#	source='src/socket/inproc/xinproc.c' object='xinproc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xinproc.lo `test -f 'src/socket/inproc/xinproc.c' || echo '$(srcdir)/'`src/socket/inproc/xinproc.c

xinproc_listener.lo: src/socket/inproc/xinproc_listener.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xinproc_listener.lo -MD -MP -MF $(DEPDIR)/xinproc_listener.Tpo -c -o xinproc_listener.lo `test -f 'src/socket/inproc/xinproc_listener.c' || echo '$(srcdir)/'`src/socket/inproc/xinproc_listener.c
	$(am__mv) $(DEPDIR)/xinproc_listener.Tpo $(DEPDIR)/xinproc_listener.Plo
#	source='src/socket/inproc/xinproc_listener.c' object='xinproc_listener.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xinproc_listener.lo `test -f 'src/socket/inproc/xinproc_listener.c' || echo '$(srcdir)/'`src/socket/inproc/xinproc_listener.c

xpoll_struct.lo: src/poll/xpoll_struct.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xpoll_struct.lo -MD -MP -MF $(DEPDIR)/xpoll_struct.Tpo -c -o xpoll_struct.lo `test -f 'src/poll/xpoll_struct.c' || echo '$(srcdir)/'`src/poll/xpoll_struct.c
	$(am__mv) $(DEPDIR)/xpoll_struct.Tpo $(DEPDIR)/xpoll_struct.Plo
#	source='src/poll/xpoll_struct.c' object='xpoll_struct.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xpoll_struct.lo `test -f 'src/poll/xpoll_struct.c' || echo '$(srcdir)/'`src/poll/xpoll_struct.c

xselect.lo: src/poll/xselect.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xselect.lo -MD -MP -MF $(DEPDIR)/xselect.Tpo -c -o xselect.lo `test -f 'src/poll/xselect.c' || echo '$(srcdir)/'`src/poll/xselect.c
	$(am__mv) $(DEPDIR)/xselect.Tpo $(DEPDIR)/xselect.Plo
#	source='src/poll/xselect.c' object='xselect.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xselect.lo `test -f 'src/poll/xselect.c' || echo '$(srcdir)/'`src/poll/xselect.c

xeventpoll.lo: src/poll/xeventpoll.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT xeventpoll.lo -MD -MP -MF $(DEPDIR)/xeventpoll.Tpo -c -o xeventpoll.lo `test -f 'src/poll/xeventpoll.c' || echo '$(srcdir)/'`src/poll/xeventpoll.c
	$(am__mv) $(DEPDIR)/xeventpoll.Tpo $(DEPDIR)/xeventpoll.Plo
#	source='src/poll/xeventpoll.c' object='xeventpoll.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o xeventpoll.lo `test -f 'src/poll/xeventpoll.c' || echo '$(srcdir)/'`src/poll/xeventpoll.c

sp_module.lo: src/sp/sp_module.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_module.lo -MD -MP -MF $(DEPDIR)/sp_module.Tpo -c -o sp_module.lo `test -f 'src/sp/sp_module.c' || echo '$(srcdir)/'`src/sp/sp_module.c
	$(am__mv) $(DEPDIR)/sp_module.Tpo $(DEPDIR)/sp_module.Plo
#	source='src/sp/sp_module.c' object='sp_module.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_module.lo `test -f 'src/sp/sp_module.c' || echo '$(srcdir)/'`src/sp/sp_module.c

sp_getopt.lo: src/sp/sp_getopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_getopt.lo -MD -MP -MF $(DEPDIR)/sp_getopt.Tpo -c -o sp_getopt.lo `test -f 'src/sp/sp_getopt.c' || echo '$(srcdir)/'`src/sp/sp_getopt.c
	$(am__mv) $(DEPDIR)/sp_getopt.Tpo $(DEPDIR)/sp_getopt.Plo
#	source='src/sp/sp_getopt.c' object='sp_getopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_getopt.lo `test -f 'src/sp/sp_getopt.c' || echo '$(srcdir)/'`src/sp/sp_getopt.c

sp_close.lo: src/sp/sp_close.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_close.lo -MD -MP -MF $(DEPDIR)/sp_close.Tpo -c -o sp_close.lo `test -f 'src/sp/sp_close.c' || echo '$(srcdir)/'`src/sp/sp_close.c
	$(am__mv) $(DEPDIR)/sp_close.Tpo $(DEPDIR)/sp_close.Plo
#	source='src/sp/sp_close.c' object='sp_close.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_close.lo `test -f 'src/sp/sp_close.c' || echo '$(srcdir)/'`src/sp/sp_close.c

sp_add.lo: src/sp/sp_add.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_add.lo -MD -MP -MF $(DEPDIR)/sp_add.Tpo -c -o sp_add.lo `test -f 'src/sp/sp_add.c' || echo '$(srcdir)/'`src/sp/sp_add.c
	$(am__mv) $(DEPDIR)/sp_add.Tpo $(DEPDIR)/sp_add.Plo
#	source='src/sp/sp_add.c' object='sp_add.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_add.lo `test -f 'src/sp/sp_add.c' || echo '$(srcdir)/'`src/sp/sp_add.c

sp_endpoint.lo: src/sp/sp_endpoint.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_endpoint.lo -MD -MP -MF $(DEPDIR)/sp_endpoint.Tpo -c -o sp_endpoint.lo `test -f 'src/sp/sp_endpoint.c' || echo '$(srcdir)/'`src/sp/sp_endpoint.c
	$(am__mv) $(DEPDIR)/sp_endpoint.Tpo $(DEPDIR)/sp_endpoint.Plo
#	source='src/sp/sp_endpoint.c' object='sp_endpoint.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_endpoint.lo `test -f 'src/sp/sp_endpoint.c' || echo '$(srcdir)/'`src/sp/sp_endpoint.c

sp_send.lo: src/sp/sp_send.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_send.lo -MD -MP -MF $(DEPDIR)/sp_send.Tpo -c -o sp_send.lo `test -f 'src/sp/sp_send.c' || echo '$(srcdir)/'`src/sp/sp_send.c
	$(am__mv) $(DEPDIR)/sp_send.Tpo $(DEPDIR)/sp_send.Plo
#	source='src/sp/sp_send.c' object='sp_send.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_send.lo `test -f 'src/sp/sp_send.c' || echo '$(srcdir)/'`src/sp/sp_send.c

pipeline.lo: src/sp/reqrep/pipeline.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT pipeline.lo -MD -MP -MF $(DEPDIR)/pipeline.Tpo -c -o pipeline.lo `test -f 'src/sp/reqrep/pipeline.c' || echo '$(srcdir)/'`src/sp/reqrep/pipeline.c
	$(am__mv) $(DEPDIR)/pipeline.Tpo $(DEPDIR)/pipeline.Plo
#	source='src/sp/reqrep/pipeline.c' object='pipeline.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o pipeline.lo `test -f 'src/sp/reqrep/pipeline.c' || echo '$(srcdir)/'`src/sp/reqrep/pipeline.c

rep_ep.lo: src/sp/reqrep/rep_ep.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rep_ep.lo -MD -MP -MF $(DEPDIR)/rep_ep.Tpo -c -o rep_ep.lo `test -f 'src/sp/reqrep/rep_ep.c' || echo '$(srcdir)/'`src/sp/reqrep/rep_ep.c
	$(am__mv) $(DEPDIR)/rep_ep.Tpo $(DEPDIR)/rep_ep.Plo
#	source='src/sp/reqrep/rep_ep.c' object='rep_ep.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rep_ep.lo `test -f 'src/sp/reqrep/rep_ep.c' || echo '$(srcdir)/'`src/sp/reqrep/rep_ep.c

req_ep.lo: src/sp/reqrep/req_ep.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT req_ep.lo -MD -MP -MF $(DEPDIR)/req_ep.Tpo -c -o req_ep.lo `test -f 'src/sp/reqrep/req_ep.c' || echo '$(srcdir)/'`src/sp/reqrep/req_ep.c
	$(am__mv) $(DEPDIR)/req_ep.Tpo $(DEPDIR)/req_ep.Plo
#	source='src/sp/reqrep/req_ep.c' object='req_ep.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o req_ep.lo `test -f 'src/sp/reqrep/req_ep.c' || echo '$(srcdir)/'`src/sp/reqrep/req_ep.c

sp_rm.lo: src/sp/sp_rm.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_rm.lo -MD -MP -MF $(DEPDIR)/sp_rm.Tpo -c -o sp_rm.lo `test -f 'src/sp/sp_rm.c' || echo '$(srcdir)/'`src/sp/sp_rm.c
	$(am__mv) $(DEPDIR)/sp_rm.Tpo $(DEPDIR)/sp_rm.Plo
#	source='src/sp/sp_rm.c' object='sp_rm.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_rm.lo `test -f 'src/sp/sp_rm.c' || echo '$(srcdir)/'`src/sp/sp_rm.c

sp_hdr.lo: src/sp/sp_hdr.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_hdr.lo -MD -MP -MF $(DEPDIR)/sp_hdr.Tpo -c -o sp_hdr.lo `test -f 'src/sp/sp_hdr.c' || echo '$(srcdir)/'`src/sp/sp_hdr.c
	$(am__mv) $(DEPDIR)/sp_hdr.Tpo $(DEPDIR)/sp_hdr.Plo
#	source='src/sp/sp_hdr.c' object='sp_hdr.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_hdr.lo `test -f 'src/sp/sp_hdr.c' || echo '$(srcdir)/'`src/sp/sp_hdr.c

sp_recv.lo: src/sp/sp_recv.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_recv.lo -MD -MP -MF $(DEPDIR)/sp_recv.Tpo -c -o sp_recv.lo `test -f 'src/sp/sp_recv.c' || echo '$(srcdir)/'`src/sp/sp_recv.c
	$(am__mv) $(DEPDIR)/sp_recv.Tpo $(DEPDIR)/sp_recv.Plo
#	source='src/sp/sp_recv.c' object='sp_recv.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_recv.lo `test -f 'src/sp/sp_recv.c' || echo '$(srcdir)/'`src/sp/sp_recv.c

sp_setopt.lo: src/sp/sp_setopt.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT sp_setopt.lo -MD -MP -MF $(DEPDIR)/sp_setopt.Tpo -c -o sp_setopt.lo `test -f 'src/sp/sp_setopt.c' || echo '$(srcdir)/'`src/sp/sp_setopt.c
	$(am__mv) $(DEPDIR)/sp_setopt.Tpo $(DEPDIR)/sp_setopt.Plo
#	source='src/sp/sp_setopt.c' object='sp_setopt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o sp_setopt.lo `test -f 'src/sp/sp_setopt.c' || echo '$(srcdir)/'`src/sp/sp_setopt.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(pkgconfigdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(pkgconfigdir)" && rm -f $$files
install-xincludeHEADERS: $(xinclude_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(xincludedir)" || $(MKDIR_P) "$(DESTDIR)$(xincludedir)"
	@list='$(xinclude_HEADERS)'; test -n "$(xincludedir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(xincludedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(xincludedir)" || exit $$?; \
	done

uninstall-xincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(xinclude_HEADERS)'; test -n "$(xincludedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(xincludedir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(xincludedir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(xincludedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-pkgconfigDATA install-xincludeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLTLIBRARIES uninstall-pkgconfigDATA \
	uninstall-xincludeHEADERS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libLTLIBRARIES clean-libtool ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-man install-pdf install-pdf-am install-pkgconfigDATA \
	install-ps install-ps-am install-strip install-xincludeHEADERS \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-libLTLIBRARIES \
	uninstall-pkgconfigDATA uninstall-xincludeHEADERS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
